# Generated by Django 4.1 on 2024-10-29 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpay',
            name='achivement_reward',
            field=models.IntegerField(default=0),
        ),
    ]
