# Generated by Django 4.1 on 2024-11-18 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_manager', '0004_alter_mpay_net_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpaygrade',
            name='basic_amt',
            field=models.IntegerField(default=100000),
        ),
        migrations.AlterField(
            model_name='mpaygrade',
            name='da_amt',
            field=models.IntegerField(default=22000),
        ),
        migrations.AlterField(
            model_name='mpaygrade',
            name='medical_amt',
            field=models.IntegerField(default=10000),
        ),
        migrations.AlterField(
            model_name='mpaygrade',
            name='pf_amt',
            field=models.IntegerField(default=12000),
        ),
    ]
